### ISSUE TITLE
Mimick issue for ros2 foxy - debian 10 i386

### ISSUE THREAD

**Issue by BhanuKiranChaluvadi** [ros2/Mimick#19] opened 2021-01-19 21:09 UTC
I am using docker container (`docker pull i386/debian:10.7`). As usual I followed instructions to [install ros2 foxy](https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Development-Setup/) from official webpage.
After performing colcon build,  mimick-ext fails.  

```
Starting >>> mimick_vendor
--- stderr: mimick_vendor                                                                                                                                
Cloning into 'mimick-ext'...
Note: checking out 'f171450b5ebaa3d2538c762a059dfc6ab7a01039'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at f171450 Add armv7l as a 32-bit ARM architecture. (#16)
/root/ros2_foxy/build/mimick_vendor/mimick-ext-prefix/src/mimick-ext/src/asm/trampoline-x86_64-systemv.S: Assembler messages:
/root/ros2_foxy/build/mimick_vendor/mimick-ext-prefix/src/mimick-ext/src/asm/trampoline-x86_64-systemv.S:39: Error: bad register name `%r11'
/root/ros2_foxy/build/mimick_vendor/mimick-ext-prefix/src/mimick-ext/src/asm/trampoline-x86_64-systemv.S:41: Error: bad register name `%r11'
/root/ros2_foxy/build/mimick_vendor/mimick-ext-prefix/src/mimick-ext/src/asm/trampoline-x86_64-systemv.S:42: Error: bad register name `%r11)'
/root/ros2_foxy/build/mimick_vendor/mimick-ext-prefix/src/mimick-ext/src/asm/trampoline-x86_64-systemv.S:44: Error: bad register name `%rdi'
/root/ros2_foxy/build/mimick_vendor/mimick-ext-prefix/src/mimick-ext/src/asm/trampoline-x86_64-systemv.S:45: Error: bad register name `%rsi'
/root/ros2_foxy/build/mimick_vendor/mimick-ext-prefix/src/mimick-ext/src/asm/trampoline-x86_64-systemv.S:46: Error: bad register name `%rdx'
/root/ros2_foxy/build/mimick_vendor/mimick-ext-prefix/src/mimick-ext/src/asm/trampoline-x86_64-systemv.S:47: Error: bad register name `%rcx'
.....
.....
.....
/root/ros2_foxy/build/mimick_vendor/mimick-ext-prefix/src/mimick-ext/src/asm/trampoline-x86_64-systemv.S:100: Error: bad register name `%r11'
make[5]: *** [CMakeFiles/mimick.dir/build.make:63: CMakeFiles/mimick.dir/src/asm/trampoline-x86_64-systemv.S.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:112: CMakeFiles/mimick.dir/all] Error 2
make[3]: *** [Makefile:141: all] Error 2
make[2]: *** [CMakeFiles/mimick-ext.dir/build.make:111: mimick-ext-prefix/src/mimick-ext-stamp/mimick-ext-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/mimick-ext.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< mimick_vendor [15.9s, exited with code 2]
```

I am also not quite sure, why its refering to 32-bit ARM architecture. It should be 32bit AMD instead

**Comment by clalancette** [comment] 2021-02-04 14:02
The problem is definitely that you are on 32-bit x86.  You can see it by this error:

```
Error: bad register name `%r11'
```

r11 is a register in x86_64, but not in i386.

To make this work, you'll either have to switch to x86_64 (that would be my suggestion), or you'll have to implement support in mimick for i386.  Note that we don't support i386 at all in ROS 2, so there may be other issues you come across.

I'm going to close this out since we don't really plan on support i386, but if you implement that support do feel free to open a pull request and we'll be happy to review it.

**Closed by clalancette** 2021-02-04 14:02 UTC

**Comment by BhanuKiranChaluvadi** [comment] 2021-02-04 15:28
I managed to build ros2 foxy but with out Mimick by turning off all the tests. Your README page says that it support linux x86 and hence i posted it here.
